services:
    loki:
        image: grafana/loki:latest
        command: [ "-config.file=/etc/loki/loki-config.yaml" ]
        ports:
            - "3100:3100"
        volumes:
            - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
            - loki-data:/tmp/loki
        restart: unless-stopped

    tempo:
        image: grafana/tempo:latest
        command: [ "-config.file=/etc/tempo/tempo.yaml" ]
        ports:
            - "3200:3200"   # Tempo HTTP API
            - "4317:4317"   # OTLP gRPC
            - "4318:4318"   # OTLP HTTP
        volumes:
            - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
            - tempo-data:/var/tempo
        restart: unless-stopped

    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            # 开启一些 Trace 相关新特性（可选）
            - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor,tempoApmTable,nodeGraph
        volumes:
            - grafana-data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning:ro
        depends_on:
            - loki
            - tempo
        restart: unless-stopped

volumes:
    loki-data:
    tempo-data:
    grafana-data:
