#!/usr/bin/env just --justfile

export PATH := join(justfile_directory(), "node_modules", "bin") + ":" + env_var('PATH')

dev-dashboard:
    pnpm i && pnpm ng build --configuration development

prod-dashboard:
    pnpm i && pnpm ng build --configuration production
