#!/usr/bin/env just --justfile

export PATH := join(justfile_directory(), "node_modules", "bin") + ":" + env_var('PATH')

build-dev:
    pnpm i && pnpm ng build --configuration development

build-prod:
    pnpm i && pnpm ng build --configuration production
