apiVersion: 1
datasources:
    -   name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: true
        jsonData:
            maxLines: 1000
            derivedFields:
                -   name: trace_id
                    matcherRegex: 'trace[_-]?id["=: ]+([0-9A-Fa-f]{16,32})'
                    matcherType: regex
                    datasourceUid: tempo
                    url: "$${__value.raw}"  # 内部链接到 Tempo，值就是 trace_id

    -   name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        jsonData:
            nodeGraph:
                enabled: true
            search:
                hide: false
