name: Trigger auto deployment for convertor

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/convertor-AutoDeployTrigger-89f6bfd4-f55a-4c89-90ff-3658c9ad001a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONVERTOR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONVERTOR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONVERTOR_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.CONVERTOR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONVERTOR_REGISTRY_PASSWORD }}
          containerAppName: convertor
          resourceGroup: BppleMan
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


